### ISSUE TITLE
Create Workout Plan Class

### ISSUE THREAD

**Issue by Anatherium** [CS361-Oregon-State-University/Hexagon#20]
Members:
completion (int)
week1Exercises[] (workoutType)
week2Exercises[] (workoutType)
week3Exercises[] (workoutType)
week4Exercises[] (workoutType)
Goal (Goal)

Methods:
getters for completion and Goal
setters for completion, Goal
setWorkoutPlan()
displayCurrentWorkoutPlan
displayWorkoutSummary

**Comment by PeterMoraStevens** [comment]
Finished workout plan class
