### ISSUE TITLE
Create Lesson Class

### ISSUE THREAD

**Issue by Anatherium** [CS361-Oregon-State-University/Hexagon#29]
Members:
topic (String)
learningArticle (String)
video (video)

Methods:
getters and setters

**Comment by PeterMoraStevens** [comment]
Lesson class has been created -> next step is to instantiate lessons so we can add them to courses 👍 :)
<img width="366" alt="Screenshot 2024-03-04 at 1 46 09 PM" src="https://github.com/CS361-Oregon-State-University/Hexagon/assets/97086965/b260f7fc-d8f3-4f84-96c2-0015d84d9b8f">
