### ISSUE TITLE
Create Course Class

### ISSUE THREAD

**Issue by Anatherium** [CS361-Oregon-State-University/Hexagon#30]
Members:
lessons[] (Lesson)

Methods:
addLesson
removeLesson
getLesson

**Comment by PeterMoraStevens** [comment]
Courses class has been finished -> need to create courses for library and store some lessons in the courses
<img width="473" alt="Screenshot 2024-03-04 at 1 55 32 PM" src="https://github.com/CS361-Oregon-State-University/Hexagon/assets/97086965/e7ae3ca8-cea3-4450-bd68-65b03725a360">
