### ISSUE TITLE
Create Library Class

### ISSUE THREAD

**Issue by Anatherium** [CS361-Oregon-State-University/Hexagon#31]
Members:
workouts (workout)

Methods:
getter and setter for workouts
sortLibrary
removeWorkout

**Comment by PeterMoraStevens** [comment]
Finished Library -> will create example workouts then code more classes
<img width="710" alt="Screenshot 2024-03-04 at 2 06 18 PM" src="https://github.com/CS361-Oregon-State-University/Hexagon/assets/97086965/df7a72f0-f922-4418-aa96-341ffbd0d66b">
